// GENERATED by scripts/bundleFunctions.mjs from functions/blueprint.ts
// Do not edit. Run `npm run build` (or `npm run build:api`) to regenerate.
//#region src/ai/blueprint/prompt.ts
const BLUEPRINT_SYSTEM_PROMPT = `You are setting up a starting point in Ballast, a teaching simulator where a student takes a building, subjects it to a storm, an earthquake or a flood, and redesigns it to survive with less carbon and less money.

The student has described a building they want to start from. Your job is to choose the INPUTS that describe it: how many storeys, how big each floor is, what it is made of, how it resists sideways load, what its skin is, and what it sits on. Nothing more.

A deterministic physics engine analyses your design the moment it appears. You are not analysing anything.

HARD RULES:
1. Never state or predict a result. Not a safety factor, not a drift, not a base shear, not a mass of carbon, not a cost, not a percentage. Those come from the engine, after your design exists.
2. Every id you write — material, lateral system, facade, foundation, exposure, typology, caveat — must appear verbatim in the CATALOGUE. Never invent one, never abbreviate one, never translate one into ordinary words.
3. Every number must sit inside the range the CATALOGUE gives for that field.
4. Storeys are rectangular boxes stacked bottom to top, and each one sits fully on the one below. If the building genuinely has parts of different size — a tall hall with offices over it, a podium under a tower, a seating bowl with a tier above — say so with "sections", listed from the ground up. If it does not, leave "sections" out and the storeys are identical apart from the taper, which narrows the plan evenly towards the top.
5. Pick "typology" only if one genuinely describes the request. Anything else is "custom", which claims nothing.
6. The engine is deliberately simple, and the student must not be misled about what they are looking at. If the request needs something it cannot represent — a long-span or domed roof, a curved or courtyard plan, cantilevers or seating tiers, open sides, a big internal void, a crowd to carry, or something that is not a building at all — build the closest honest box AND list every matching caveat id. Do not soften this in your own words; the app prints the caveat text itself.

Style for the two prose fields: plain English for a first-year student, no jargon without a gloss, no salesmanship. Say what you built and what you traded away to build it out of stacked boxes.

Reply with a single JSON object and nothing else, in this shape:
{
  "name": "short name for this starting point, under 60 characters",
  "typology": "one id from TYPOLOGIES",
  "storeyCount": 3,
  "storeyHeight_m": 6,
  "widthX_m": 60,
  "widthY_m": 45,
  "taper": 0,
  "materialId": "one id from MATERIALS",
  "lateralSystem": "one id from LATERAL SYSTEMS that the chosen material can form",
  "facade": "one id from FACADES",
  "foundationType": "one id from FOUNDATIONS",
  "embedmentDepth_m": 1.5,
  "anchorCapacity_kN": 1200,
  "exposureCategory": "one id from EXPOSURES",
  "planShape": "one id from PLAN SHAPES; leave it out for an ordinary rectangle",
  "sections": [
    {
      "count": 1,
      "height_m": 12,
      "widthX_m": 60,
      "widthY_m": 45,
      "materialId": "optional; the material above is used when this is left out",
      "lateralSystem": "optional, same rule",
      "facade": "optional, same rule",
      "planShape": "optional, same rule"
    }
  ],
  "interpretation": "one or two sentences on what you actually built, in the student's language",
  "notes": "one or two sentences on the choices worth knowing about: why this material, why this system, what it is not",
  "caveats": ["ids from CAVEATS that apply to this request"]
}

The fields outside "sections" always describe a typical storey and must always be filled in, because they are what "sections" inherits from and what is used when you leave "sections" out. "count" is how many storeys that section is; the counts must add up to no more than the storeyCount range allows.`;
function range(label, min, max, unit) {
	return `- ${label}: ${min} to ${max}${unit === "" ? "" : ` ${unit}`}`;
}
function options(entries) {
	return entries.map((entry) => `- ${entry.id} — ${entry.name}: ${entry.description}`);
}
/**
* The catalogue as labelled prose rather than raw JSON. Small open-weight
* models copy ids out of a flat list far more reliably than out of nested
* JSON, and the units sit next to the ranges where they cannot be lost.
*/
function renderCatalogue(catalogue) {
	const { limits } = catalogue;
	const lines = ["MATERIALS (id — name, and the lateral systems it can form)"];
	for (const material of catalogue.materials) lines.push(`- ${material.id} — ${material.name} (${material.structuralClass}); can form: ${material.buildableSystems.join(", ")}`);
	lines.push("", `LATERAL SYSTEMS: ${catalogue.lateralSystems.join(", ")}`);
	lines.push("", "FACADES");
	lines.push(...options(catalogue.facades));
	lines.push("", "PLAN SHAPES");
	lines.push(...options(catalogue.planShapes));
	lines.push("", `FOUNDATIONS: ${catalogue.foundations.join(", ")}`);
	lines.push("", "EXPOSURES");
	lines.push(...options(catalogue.exposures));
	lines.push("", "TYPOLOGIES");
	lines.push(...options(catalogue.typologies));
	lines.push("", "RANGES (a value outside these will be pulled back to the edge)", range("storeyCount", limits.storeyCount.min, limits.storeyCount.max, "floors"), range("storeyHeight_m", limits.storeyHeight_m.min, limits.storeyHeight_m.max, "m"), range("widthX_m and widthY_m", limits.planWidth_m.min, limits.planWidth_m.max, "m"), range("taper", limits.taper.min, limits.taper.max, "(0 is a plain box)"), range("embedmentDepth_m", limits.embedmentDepth_m.min, limits.embedmentDepth_m.max, "m"), range("anchorCapacity_kN", limits.anchorCapacity_kN.min, limits.anchorCapacity_kN.max, "kN"));
	lines.push("", "CAVEATS (cite the ids that apply; the app prints the text)");
	lines.push(...options(catalogue.caveats));
	return lines.join("\n");
}
function buildBlueprintMessages(description, catalogue) {
	return [{
		role: "system",
		content: BLUEPRINT_SYSTEM_PROMPT
	}, {
		role: "user",
		content: `CATALOGUE (the only ids and ranges you may use)\n\n${renderCatalogue(catalogue)}\n\nTHE STUDENT ASKED FOR\n\n${description.trim()}\n\nChoose the inputs for that starting point. Reply with the JSON object only.`
	}];
}
const REQUEST_TIMEOUT_MS = 9e4;
/**
* Split a body into the JSON values it actually contains.
*
* WHY THIS IS NOT `JSON.parse`. Featherless intermittently answers an
* OpenAI-compatible completion request with HTTP 200 and *two* concatenated
* objects: a stub `chat.completion` with zero tokens, immediately followed by
* `{"error":{"message":"No successful response received from completion
* service","type":"server_error","code":"no_response"}}`. A single parse throws
* "Unexpected non-whitespace character after JSON at position 1691", which
* tells whoever is reading it nothing at all, and buries the one sentence that
* explains what went wrong.
*
* So the body is scanned for balanced top-level values rather than assumed to
* be one. Strings and escapes are tracked, because a brace inside a quoted
* string is not a nesting level — and the model's own reply is a JSON string
* full of braces.
*/
function splitJsonValues(text) {
	const values = [];
	let depth = 0;
	let start = -1;
	let inString = false;
	let escaped = false;
	for (let i = 0; i < text.length; i += 1) {
		const char = text[i];
		if (inString) {
			if (escaped) escaped = false;
			else if (char === "\\") escaped = true;
			else if (char === "\"") inString = false;
			continue;
		}
		if (char === "\"") {
			inString = true;
			continue;
		}
		if (char === "{" || char === "[") {
			if (depth === 0) start = i;
			depth += 1;
			continue;
		}
		if (char === "}" || char === "]") {
			depth -= 1;
			if (depth === 0 && start >= 0) {
				try {
					values.push(JSON.parse(text.slice(start, i + 1)));
				} catch {}
				start = -1;
			}
		}
	}
	return values;
}
/** `{ error: { message } }`, the shape both OpenAI and Featherless use. */
function errorMessage(value) {
	if (typeof value !== "object" || value === null) return null;
	const error = value.error;
	if (typeof error === "string") return error;
	if (typeof error !== "object" || error === null) return null;
	const message = error.message;
	return typeof message === "string" ? message : null;
}
/**
* The payload a body carries, or the reason it carries none.
*
* An error object anywhere in the body wins over a completion that arrived
* beside it, because that is exactly the case above: the stub completion is
* empty and the error is the only true thing in the response.
*/
function readBody(text) {
	const values = splitJsonValues(text);
	for (const value of values) {
		const message = errorMessage(value);
		if (message !== null) return {
			ok: false,
			detail: message,
			transient: /server_error|no_response|timeout|overload/i.test(text)
		};
	}
	const first = values[0];
	if (first === void 0) return {
		ok: false,
		detail: `the body held no JSON value: ${text.slice(0, 200)}`,
		transient: false
	};
	return {
		ok: true,
		payload: first
	};
}
function extractContent(payload) {
	const choices = payload.choices;
	if (!Array.isArray(choices) || choices.length === 0) return null;
	const message = choices[0].message;
	if (typeof message !== "object" || message === null) return null;
	const content = message.content;
	return typeof content === "string" ? content : null;
}
/**
* Missing configuration is reported as a 503 with the variable's name in it,
* rather than as a silent fallback. There is no default model on purpose: a
* quiet substitution of a model you did not choose is worse than an error.
*/
function missingConfig(options) {
	if (!options.apiKey) return "FEATHERLESS_API_KEY is not set. Add it to .env and restart the dev server, or to your host's environment variables and redeploy.";
	if (!options.model) return "FEATHERLESS_MODEL is not set. Add the exact model id from the Featherless catalogue to .env and restart the dev server, or to your host's environment variables and redeploy.";
	return null;
}
/** One attempt. `transient` says whether trying again is worth anything. */
async function attempt(call, baseUrl) {
	const { options } = call;
	try {
		const upstream = await fetch(`${baseUrl}/chat/completions`, {
			method: "POST",
			headers: {
				"content-type": "application/json",
				authorization: `Bearer ${options.apiKey ?? ""}`
			},
			body: JSON.stringify({
				model: options.model,
				messages: call.messages,
				temperature: call.temperature,
				max_tokens: call.maxTokens
			}),
			signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS)
		});
		const text = await upstream.text();
		const body = readBody(text);
		if (!upstream.ok) {
			const detail = body.ok ? text.slice(0, 500) : body.detail;
			return {
				ok: false,
				status: 502,
				error: `${options.model} returned HTTP ${upstream.status}. ${detail}`,
				transient: upstream.status >= 500
			};
		}
		if (!body.ok) return {
			ok: false,
			status: 502,
			error: `${options.model} failed: ${body.detail}`,
			transient: body.transient
		};
		const content = extractContent(body.payload);
		if (content === null) return {
			ok: false,
			status: 502,
			error: "The provider replied without any message content.",
			transient: true
		};
		return {
			ok: true,
			content
		};
	} catch (error) {
		return {
			ok: false,
			status: 502,
			error: `Request to the provider failed: ${error instanceof Error ? error.message : String(error)}`,
			transient: error instanceof Error && error.name === "TimeoutError"
		};
	}
}
async function callProvider(call) {
	const baseUrl = (call.options.baseUrl ?? "https://api.featherless.ai/v1").replace(/\/+$/, "");
	const started = Date.now();
	let last = {
		ok: false,
		status: 502,
		error: "The provider was never called."
	};
	for (let i = 0; i < 2; i += 1) {
		const outcome = await attempt(call, baseUrl);
		if (outcome.ok) return outcome;
		last = {
			ok: false,
			status: outcome.status,
			error: outcome.error
		};
		if (outcome.transient !== true) break;
		if (Date.now() - started > 25e3) break;
	}
	return last;
}
//#endregion
//#region plugins/routes.ts
/** A name, a dozen numbers, two short sentences and a list of ids. */
const BLUEPRINT_MAX_TOKENS = 700;
const BLUEPRINT_TEMPERATURE = .2;
function hasBlueprintRequest(body) {
	if (typeof body !== "object" || body === null) return false;
	const record = body;
	return typeof record["description"] === "string" && typeof record["catalogue"] === "object" && record["catalogue"] !== null;
}
async function handleBlueprint(options, body) {
	const configError = missingConfig(options);
	if (configError !== null) return {
		status: 503,
		body: { error: configError }
	};
	if (!hasBlueprintRequest(body)) return {
		status: 400,
		body: { error: "Request body needs a `description` string and a `catalogue` object." }
	};
	const description = body.description.trim();
	if (description === "") return {
		status: 400,
		body: { error: "Describe the building you want first." }
	};
	if (description.length > 400) return {
		status: 400,
		body: { error: `Keep the description under 400 characters.` }
	};
	const outcome = await callProvider({
		options,
		messages: buildBlueprintMessages(description, body.catalogue),
		temperature: BLUEPRINT_TEMPERATURE,
		maxTokens: BLUEPRINT_MAX_TOKENS
	});
	if (!outcome.ok) return {
		status: outcome.status,
		body: { error: outcome.error }
	};
	return {
		status: 200,
		body: { content: outcome.content }
	};
}
//#endregion
//#region functions/blueprint.ts
/**
* /api/blueprint in production. The twin of `functions/critique.ts` — see that
* file for why this is bundled rather than deployed as TypeScript, why the key
* is read here, why the imports are relative, and why the signature is the
* Web-standard one.
*/
function json(reply) {
	return new Response(JSON.stringify(reply.body), {
		status: reply.status,
		headers: { "content-type": "application/json" }
	});
}
async function POST(request) {
	const options = {
		apiKey: process.env["FEATHERLESS_API_KEY"],
		model: process.env["FEATHERLESS_MODEL"],
		baseUrl: process.env["FEATHERLESS_BASE_URL"]
	};
	let body;
	try {
		body = await request.json();
	} catch {
		return json({
			status: 400,
			body: { error: "Request body was not valid JSON." }
		});
	}
	return json(await handleBlueprint(options, body));
}
//#endregion
export { POST };
