// GENERATED by scripts/bundleFunctions.mjs from functions/critique.ts
// Do not edit. Run `npm run build` (or `npm run build:api`) to regenerate.
//#region src/ai/prompt.ts
const SYSTEM_PROMPT = `You are a structural engineering tutor helping a first-year student understand why their building design passes or fails under a natural hazard: a wind storm, an earthquake, or a flood. The FACTS say which one, and the three behave very differently — wind pushes hardest at the top, an earthquake's force grows with the building's own weight, and a flood loads the bottom and tries to float it. Explain the one you were given.

A deterministic physics engine has already analysed the design. Its results are given to you as FACTS. Your job is to explain and advise. It is not to calculate.

HARD RULES:
1. Never compute, estimate, derive or invent a number. Not a force, not a safety factor, not a percentage, not a cost, not a mass.
2. You may quote a figure only if it appears verbatim in the FACTS. Quote it exactly as written there, including its units.
3. If your point needs a quantity that is not in the FACTS, make the point in words instead. "The upper storeys carry noticeably less load" is correct; inventing the figure is not.
4. Do not predict what a change would produce numerically. Say a change would reduce drift; never say by how much. The student will apply it and the engine will tell them.
5. Only recommend materials and lateral systems listed in the FACTS.
6. Do not advise about a hazard you were not given. If the FACTS describe a flood, do not talk about wind speeds; the student chose one event and is looking at its numbers.

Style: plain English, no jargon without a gloss, warm but direct. A student reads this to learn, not to be flattered.

Reply with a single JSON object and nothing else, in this shape:
{
  "verdict": "one sentence, under 20 words, on whether this design stands up",
  "explanation": "60-120 words on WHY the governing failure mode is what it is, in physical terms the student can picture",
  "suggestions": [
    {
      "change": "one concrete edit the student can make with the controls",
      "rationale": "why it addresses the governing problem",
      "tradeoff": "what it costs in carbon, money or space"
    }
  ]
}

Give two or three suggestions. Every suggestion must name a real tradeoff; a change with no downside is almost always a change you have not thought through.`;
function fixed(value, decimals) {
	if (!Number.isFinite(value)) return "not governing (no finite value)";
	return value.toFixed(decimals);
}
function driftText(denominator) {
	return Number.isFinite(denominator) ? `h/${denominator}` : "negligible";
}
/**
* The hazard block, which is the one part of the fact sheet that differs
* between the three events.
*
* Only the lines the hazard actually has. A `CritiqueHazard` leaves the fields
* that do not apply undefined, so this reads them rather than printing
* "gust speed: 0 km/h" at an earthquake — which would be a figure about a
* quantity that does not exist, and a figure the guard would then happily
* accept the model quoting.
*/
function hazardLines(hazard) {
	const lines = [`- This is ${hazard.description}.`];
	if (hazard.gustSpeed_kmh !== void 0) lines.push(`- Wind gust speed: ${fixed(hazard.gustSpeed_kmh, 0)} km/h`);
	if (hazard.exposureCategory !== void 0) lines.push(`- Exposure category ${hazard.exposureCategory} (${hazard.exposureDescription ?? ""})`);
	if (hazard.Ss_g !== void 0 && hazard.S1_g !== void 0) lines.push(`- Mapped ground motion: Ss = ${fixed(hazard.Ss_g, 2)} g at short period, S1 = ${fixed(hazard.S1_g, 2)} g at one second`);
	if (hazard.SDS_g !== void 0 && hazard.SD1_g !== void 0) lines.push(`- Design accelerations after the site adjustment: SDS = ${fixed(hazard.SDS_g, 2)} g, SD1 = ${fixed(hazard.SD1_g, 2)} g`);
	if (hazard.siteClass !== void 0) lines.push(`- Site Class ${hazard.siteClass} (${hazard.siteDescription ?? ""})`);
	if (hazard.responseModificationR !== void 0) lines.push(`- Response modification factor R = ${hazard.responseModificationR}, from the weakest lateral system in the building`);
	if (hazard.approximatePeriod_s !== void 0) lines.push(`- Approximate fundamental period: ${fixed(hazard.approximatePeriod_s, 2)} s`);
	if (hazard.depth_m !== void 0) lines.push(`- Stillwater depth above grade: ${fixed(hazard.depth_m, 1)} m`);
	if (hazard.velocity_ms !== void 0) lines.push(`- Flow velocity: ${fixed(hazard.velocity_ms, 1)} m/s`);
	lines.push(`- Direction in plan: ${fixed(hazard.directionDeg, 0)} degrees`);
	return lines;
}
/**
* Renders the context as a labelled plain-text block rather than raw JSON.
* Small models quote prose facts back more reliably than they quote nested
* JSON, and the units sit next to the numbers where they cannot be lost.
*/
function renderFacts(context) {
	const { hazard, building, score, stability, limits } = context;
	const lines = [
		"HAZARD",
		...hazardLines(hazard),
		"",
		"BUILDING",
		`- ${building.storeyCount} storeys, ${fixed(building.totalHeight_m, 1)} m tall`,
		`- Plan ${fixed(building.planX_m, 1)} m by ${fixed(building.planY_m, 1)} m`,
		`- Gross floor area: ${fixed(building.floorArea_m2, 0)} m2`,
		`- Slenderness (height / narrow plan dimension): ${fixed(building.slendernessRatio, 2)}`,
		`- Foundation: ${building.foundationType}, embedded ${fixed(building.embedmentDepth_m, 2)} m, anchors ${fixed(building.anchorCapacity_kN, 0)} kN`,
		"",
		"RESULTS",
		`- Governing failure mode: ${score.governingFailureMode}`,
		`- Safety factor: ${fixed(score.safetyFactor, 2)} (target ${fixed(limits.targetSafetyFactor, 2)})`,
		`- Factor of safety against overturning: ${fixed(stability.factorOfSafetyOverturning, 2)}`,
		`- Factor of safety against sliding: ${fixed(stability.factorOfSafetySliding, 2)}`,
		...stability.factorOfSafetyFlotation === void 0 ? [] : [`- Factor of safety against flotation: ${fixed(stability.factorOfSafetyFlotation, 2)}`, `- Buoyant uplift from the water it displaces: ${fixed(stability.buoyancy_kN ?? 0, 0)} kN`],
		`- Worst storey drift: ${driftText(score.worstDriftDenominator)} (limit ${driftText(limits.driftLimitDenominator)})`,
		`- Base shear: ${fixed(stability.baseShear_kN, 1)} kN`,
		`- Overturning moment: ${fixed(stability.overturningMoment_kNm, 0)} kNm`,
		`- Restoring moment: ${fixed(stability.restoringMoment_kNm, 0)} kNm`,
		`- Total self weight: ${fixed(stability.totalSelfWeight_kN, 0)} kN`,
		"",
		"SUSTAINABILITY AND COST",
		`- Embodied carbon: ${fixed(score.carbon_kgCO2e, 0)} kg CO2e (${fixed(score.carbonIntensity_kgCO2e_m2, 1)} kgCO2e/m2)`,
		`- Cost: ${fixed(score.cost_usd, 0)} USD (${fixed(score.costIntensity_usd_m2, 0)} USD/m2)`,
		"- Scope: A1-A3, structural frame only. Costs are indicative, not surveyed.",
		"",
		"PER STOREY (1 is the ground storey)"
	];
	for (const storey of context.storeys) lines.push(`- Storey ${storey.label}: ${storey.materialName}, ${storey.lateralSystem}, ${storey.facadeName}, wind force ${fixed(storey.lateralForce_kN, 1)} kN, shear ${fixed(storey.storeyShear_kN, 1)} kN, drift ${driftText(storey.driftDenominator)}, utilisation ${fixed(storey.utilization * 100, 1)}% (drift ${fixed(storey.driftUtilization * 100, 1)}%, strength ${fixed(storey.strengthUtilization * 100, 1)}%)`);
	lines.push("", "MATERIALS AVAILABLE (the only ones you may recommend)");
	for (const material of context.materials) lines.push(`- ${material.name} (${material.structuralClass}): ${fixed(material.embodiedCarbon_kgCO2e_m3, 0)} kgCO2e/m3, ${fixed(material.cost_usd_m3, 0)} USD/m3, strength ${fixed(material.yieldStrength_MPa, 0)} MPa, density ${fixed(material.density_kg_m3, 0)} kg/m3`);
	lines.push("", "ENVELOPES AVAILABLE (the only ones you may recommend): " + context.facadeNames.join(", ") + ". Their carbon, cost and weight are already inside the figures above; you have not been given per-square-metre rates and must not quote any.");
	if (context.warnings.length > 0) {
		lines.push("", "MODELLING CAVEATS THE ENGINE REPORTED");
		for (const warning of context.warnings) lines.push(`- ${warning}`);
	}
	return lines.join("\n");
}
function buildMessages(context) {
	return [{
		role: "system",
		content: SYSTEM_PROMPT
	}, {
		role: "user",
		content: `FACTS (produced by the physics engine — every number you are allowed to use is here)\n\n${renderFacts(context)}\n\nCritique this design. Reply with the JSON object only.`
	}];
}
const REQUEST_TIMEOUT_MS = 9e4;
/**
* Split a body into the JSON values it actually contains.
*
* WHY THIS IS NOT `JSON.parse`. Featherless intermittently answers an
* OpenAI-compatible completion request with HTTP 200 and *two* concatenated
* objects: a stub `chat.completion` with zero tokens, immediately followed by
* `{"error":{"message":"No successful response received from completion
* service","type":"server_error","code":"no_response"}}`. A single parse throws
* "Unexpected non-whitespace character after JSON at position 1691", which
* tells whoever is reading it nothing at all, and buries the one sentence that
* explains what went wrong.
*
* So the body is scanned for balanced top-level values rather than assumed to
* be one. Strings and escapes are tracked, because a brace inside a quoted
* string is not a nesting level — and the model's own reply is a JSON string
* full of braces.
*/
function splitJsonValues(text) {
	const values = [];
	let depth = 0;
	let start = -1;
	let inString = false;
	let escaped = false;
	for (let i = 0; i < text.length; i += 1) {
		const char = text[i];
		if (inString) {
			if (escaped) escaped = false;
			else if (char === "\\") escaped = true;
			else if (char === "\"") inString = false;
			continue;
		}
		if (char === "\"") {
			inString = true;
			continue;
		}
		if (char === "{" || char === "[") {
			if (depth === 0) start = i;
			depth += 1;
			continue;
		}
		if (char === "}" || char === "]") {
			depth -= 1;
			if (depth === 0 && start >= 0) {
				try {
					values.push(JSON.parse(text.slice(start, i + 1)));
				} catch {}
				start = -1;
			}
		}
	}
	return values;
}
/** `{ error: { message } }`, the shape both OpenAI and Featherless use. */
function errorMessage(value) {
	if (typeof value !== "object" || value === null) return null;
	const error = value.error;
	if (typeof error === "string") return error;
	if (typeof error !== "object" || error === null) return null;
	const message = error.message;
	return typeof message === "string" ? message : null;
}
/**
* The payload a body carries, or the reason it carries none.
*
* An error object anywhere in the body wins over a completion that arrived
* beside it, because that is exactly the case above: the stub completion is
* empty and the error is the only true thing in the response.
*/
function readBody(text) {
	const values = splitJsonValues(text);
	for (const value of values) {
		const message = errorMessage(value);
		if (message !== null) return {
			ok: false,
			detail: message,
			transient: /server_error|no_response|timeout|overload/i.test(text)
		};
	}
	const first = values[0];
	if (first === void 0) return {
		ok: false,
		detail: `the body held no JSON value: ${text.slice(0, 200)}`,
		transient: false
	};
	return {
		ok: true,
		payload: first
	};
}
function extractContent(payload) {
	const choices = payload.choices;
	if (!Array.isArray(choices) || choices.length === 0) return null;
	const message = choices[0].message;
	if (typeof message !== "object" || message === null) return null;
	const content = message.content;
	return typeof content === "string" ? content : null;
}
/**
* Missing configuration is reported as a 503 with the variable's name in it,
* rather than as a silent fallback. There is no default model on purpose: a
* quiet substitution of a model you did not choose is worse than an error.
*/
function missingConfig(options) {
	if (!options.apiKey) return "FEATHERLESS_API_KEY is not set. Add it to .env and restart the dev server, or to your host's environment variables and redeploy.";
	if (!options.model) return "FEATHERLESS_MODEL is not set. Add the exact model id from the Featherless catalogue to .env and restart the dev server, or to your host's environment variables and redeploy.";
	return null;
}
/** One attempt. `transient` says whether trying again is worth anything. */
async function attempt(call, baseUrl) {
	const { options } = call;
	try {
		const upstream = await fetch(`${baseUrl}/chat/completions`, {
			method: "POST",
			headers: {
				"content-type": "application/json",
				authorization: `Bearer ${options.apiKey ?? ""}`
			},
			body: JSON.stringify({
				model: options.model,
				messages: call.messages,
				temperature: call.temperature,
				max_tokens: call.maxTokens
			}),
			signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS)
		});
		const text = await upstream.text();
		const body = readBody(text);
		if (!upstream.ok) {
			const detail = body.ok ? text.slice(0, 500) : body.detail;
			return {
				ok: false,
				status: 502,
				error: `${options.model} returned HTTP ${upstream.status}. ${detail}`,
				transient: upstream.status >= 500
			};
		}
		if (!body.ok) return {
			ok: false,
			status: 502,
			error: `${options.model} failed: ${body.detail}`,
			transient: body.transient
		};
		const content = extractContent(body.payload);
		if (content === null) return {
			ok: false,
			status: 502,
			error: "The provider replied without any message content.",
			transient: true
		};
		return {
			ok: true,
			content
		};
	} catch (error) {
		return {
			ok: false,
			status: 502,
			error: `Request to the provider failed: ${error instanceof Error ? error.message : String(error)}`,
			transient: error instanceof Error && error.name === "TimeoutError"
		};
	}
}
async function callProvider(call) {
	const baseUrl = (call.options.baseUrl ?? "https://api.featherless.ai/v1").replace(/\/+$/, "");
	const started = Date.now();
	let last = {
		ok: false,
		status: 502,
		error: "The provider was never called."
	};
	for (let i = 0; i < 2; i += 1) {
		const outcome = await attempt(call, baseUrl);
		if (outcome.ok) return outcome;
		last = {
			ok: false,
			status: outcome.status,
			error: outcome.error
		};
		if (outcome.transient !== true) break;
		if (Date.now() - started > 25e3) break;
	}
	return last;
}
//#endregion
//#region plugins/routes.ts
/**
* The two AI routes, minus HTTP.
*
* Every decision either route makes lives here: is the provider configured, is
* the body the right shape, how many tokens may the reply use, what does the
* provider's failure look like to a caller. What is deliberately absent is any
* notion of how a request arrives or an answer leaves.
*
* THAT IS WHY THIS FILE EXISTS SEPARATELY. There are two transports — the Vite
* middleware in `critiqueApi.ts` / `blueprintApi.ts` for dev and preview, and
* the Vercel functions in `api/` for production — and the second must not drag
* the first's dependencies along with it. Nothing reachable from this module
* imports Vite, not even for a type: a type-only import ought to be erased
* before any bundler tries to resolve it, but that is a bet on another tool's
* compiler, and losing it means a dev server being pulled into a serverless
* function. `routeDeps.test.ts` asserts the property rather than
* trusting this comment.
*
* The message builders it calls (`src/ai/prompt.ts`, `src/ai/blueprint/
* prompt.ts`) are pure and already shared with the browser and the tests, so
* adding a third caller costs nothing.
*/
/** Enough for a verdict, a paragraph and three suggestions, and no more. */
const CRITIQUE_MAX_TOKENS = 900;
/** Low but not zero: explanation should be steady, not robotic. */
const CRITIQUE_TEMPERATURE = .4;
function hasContext(body) {
	return typeof body === "object" && body !== null && typeof body.context === "object" && body.context !== null;
}
/**
* Takes an already-parsed body, because the two transports read one very
* differently — a Node stream in Vite, `await request.json()` on Vercel — and
* that is the only thing they should disagree about.
*/
async function handleCritique(options, body) {
	const configError = missingConfig(options);
	if (configError !== null) return {
		status: 503,
		body: { error: configError }
	};
	if (!hasContext(body)) return {
		status: 400,
		body: { error: "Request body needs a `context` object." }
	};
	const outcome = await callProvider({
		options,
		messages: buildMessages(body.context),
		temperature: CRITIQUE_TEMPERATURE,
		maxTokens: CRITIQUE_MAX_TOKENS
	});
	if (!outcome.ok) return {
		status: outcome.status,
		body: { error: outcome.error }
	};
	return {
		status: 200,
		body: { content: outcome.content }
	};
}
//#endregion
//#region functions/critique.ts
/**
* /api/critique in production.
*
* The Vite middleware in `plugins/critiqueApi.ts` serves this route during
* `npm run dev` and `npm run preview`; Vercel serves a static `dist` and has no
* Vite server, so the same route has to exist here as a function. Both are
* transports over one `handleCritique`, which is where every decision lives —
* so the token budget, the validation messages and the provider error
* passthrough cannot drift between dev and production.
*
* WHY THE KEY IS READ HERE. `vite.config.ts` reads the provider variables with
* `loadEnv(mode, cwd, '')` and hands them to the plugin; on Vercel they arrive
* as ordinary environment variables on the function. Neither path is
* `VITE_`-prefixed, because that prefix is exactly what would inline the key
* into the browser bundle. This module runs on the server and is the only place
* in production that ever sees it.
*
* THIS FILE IS NOT WHAT SHIPS. `scripts/bundleFunctions.mjs` bundles it into
* `api/critique.js`, which is what Vercel actually runs, and the reason is
* worth knowing before editing: Vercel transpiles each file under `api/` on its
* own and does not rewrite import specifiers, so an `import ... from
* '../plugins/routes.ts'` survived into the emitted JavaScript and Node threw
* ERR_MODULE_NOT_FOUND on a `.ts` path at runtime. Bundling leaves nothing to
* resolve. Edit here; never edit `api/*.js`.
*
* THREE CONSTRAINTS worth knowing:
*
*  - **Relative imports only.** Vercel's function compiler ignores tsconfig
*    "Path Mappings", so the `@/` alias the rest of the app uses would not
*    resolve here even before bundling. `../src/...` is not a style choice.
*  - **No npm package may be reachable.** `plugins/routeDeps.test.ts` asserts
*    it. Above all not Vite, whose types the dev-server transport legitimately
*    imports.
*  - **Web-standard signature.** A named method export taking a `Request` and
*    returning a `Response`, which needs no `@vercel/node` dependency and
*    leaves no ambiguity about whether the body was already parsed.
*/
function json(reply) {
	return new Response(JSON.stringify(reply.body), {
		status: reply.status,
		headers: { "content-type": "application/json" }
	});
}
async function POST(request) {
	const options = {
		apiKey: process.env["FEATHERLESS_API_KEY"],
		model: process.env["FEATHERLESS_MODEL"],
		baseUrl: process.env["FEATHERLESS_BASE_URL"]
	};
	let body;
	try {
		body = await request.json();
	} catch {
		return json({
			status: 400,
			body: { error: "Request body was not valid JSON." }
		});
	}
	return json(await handleCritique(options, body));
}
//#endregion
export { POST };
